stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bjornadalno/nginx-rp-letsencrypt:test
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
