stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bjornadalno/nginx-rp-letsencrypt:latest bjornadalno/nginx-rp-letsencrypt:test
      registry: index.docker.io
timeout: 60
notification: {}
