stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bjornadalno/nginx-rp-letsencrypt:latest
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bjornadalno/nginx-rp-letsencrypt:stable
      pushRemote: true
      registry: index.docker.io
- name: asd
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: console.log("asd");
timeout: 60
notification: {}
